### ISSUE TITLE
Add Dask Cluster class to config file 

### ISSUE THREAD

**Issue by AlecThomson** [AlecThomson/arrakis#42]
It'd be nice to steal the feature from [flint](https://github.com/tjgalvin/flint/) that allows a user to specify the Dask Cluster Class in the config YAML. @tjgalvin can this be ported into Arrakis?

**Comment by tjgalvin** [comment]
It can be. What is the current branch one should be working from?

**Comment by AlecThomson** [comment]
Lets go with `imager`

**Comment by AlecThomson** [comment]
Fixed with #49
